#!/usr/bin/php
<?php

$argv = $_SERVER["argv"];
unset($argv[0]);
$arg_string = implode(' ',$argv);
$cmd = "php application/webroot/index.php " . $arg_string;


//echo "############ calling : ". $cmd . "\n";

passthru($cmd, $code_retour);
exit($code_retour);